In [17]:
import numpy as np

from simple_net import SimpleNet
from common.gradient import numerical_gradient

In [11]:
net = SimpleNet()
print(net.W)

[[-1.17472874  0.09535884 -0.88648431]
 [-0.43335082 -0.99265423  1.6186202 ]]


In [12]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-1.09485299 -0.83617351  0.92486759]


In [13]:
np.argmax(p)

np.int64(2)

In [14]:
t = np.array([0, 0, 1])

In [15]:
net.loss(x, t)

np.float64(0.2658644452656359)

In [16]:
def f(W):
    return net.loss(x, t)

In [18]:
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.06102871  0.07904552 -0.14007422]
 [ 0.09154306  0.11856828 -0.21011134]]
