In [1]:
import dataset

In [2]:
data = dataset.download_and_load_file(dataset.file_path, dataset.url)

In [3]:
print("example: ", data[50])

example:  {'instruction': 'Identify the correct spelling of the following word.', 'input': 'Ocassion', 'output': "The correct spelling is 'Occasion.'"}


In [4]:
print("example: ", data[999])

example:  {'instruction': "What is an antonym of 'complicated'?", 'input': '', 'output': "An antonym of 'complicated' is 'simple'."}


In [5]:
from prompt import format_input

In [6]:
model_input = format_input(data[50])
desired_response = f"\n\n### Response:\n{data[50]['output']}"
print(model_input+desired_response)

Below is an instruction that describes a task.Write a response that appropriately completes the request.

### Instruction:
Identify the correct spelling of the following word.

### Input:
Ocassion

### Response:
The correct spelling is 'Occasion.'


In [7]:
train_portion = int(len(data) * 0.85)
test_portion = int(len(data) * 0.1)
val_portion = len(data) -train_portion - test_portion

train_data = data[:train_portion]
val_data = data[train_portion:train_portion+val_portion]
test_data = data[train_portion+val_portion:]

print("train: ", len(train_data), "val: ", len(val_data), "test: ", len(test_data), "total: ", len(data), "")

train:  935 val:  55 test:  110 total:  1100 


In [8]:
import tiktoken
tokenizer = tiktoken.get_encoding("gpt2")
print(tokenizer.encode("<|endoftext|>", allowed_special={"<|endoftext|>"}))

[50256]


In [9]:
inputs_1 = [0, 1, 2, 3, 4]
inputs_2 = [5, 6]
inputs_3 = [7, 8, 9]
batch = (
    inputs_1, inputs_2, inputs_3
)
print(batch)
print(dataset.custom_collate_draft_1(batch))

([0, 1, 2, 3, 4], [5, 6], [7, 8, 9])
tensor([[    0,     1,     2,     3,     4],
        [    5,     6, 50256, 50256, 50256],
        [    7,     8,     9, 50256, 50256]])


In [10]:
inputs_1 = [0, 1, 2, 3, 4]
inputs_2 = [5, 6]
inputs_3 = [7, 8, 9]
batch = (
    inputs_1, inputs_2, inputs_3
)
print(batch)
inputs, targets = dataset.custom_collate_draft_2(batch)
print(inputs)
print(targets)

([0, 1, 2, 3, 4], [5, 6], [7, 8, 9])
tensor([[    0,     1,     2,     3,     4],
        [    5,     6, 50256, 50256, 50256],
        [    7,     8,     9, 50256, 50256]])
tensor([[    1,     2,     3,     4, 50256],
        [    6, 50256, 50256, 50256, 50256],
        [    8,     9, 50256, 50256, 50256]])


In [11]:
inputs_1 = [0, 1, 2, 3, 4]
inputs_2 = [5, 6]
inputs_3 = [7, 8, 9]
batch = (
    inputs_1, inputs_2, inputs_3
)
print(batch)
inputs, targets = dataset.custom_collate_draft_fn(batch)
print(inputs)
print(targets)

([0, 1, 2, 3, 4], [5, 6], [7, 8, 9])
tensor([[    0,     1,     2,     3,     4],
        [    5,     6, 50256, 50256, 50256],
        [    7,     8,     9, 50256, 50256]])
tensor([[    1,     2,     3,     4, 50256],
        [    6, 50256,  -100,  -100,  -100],
        [    8,     9, 50256,  -100,  -100]])


In [12]:
import torch

In [13]:
logits_1 = torch.tensor([[-1.0, 1.0],
                         [-0.5, 1.5]])
targets_1 = torch.tensor([0, 1])
loss_1 = torch.nn.functional.cross_entropy(logits_1, targets_1)
print(loss_1)

tensor(1.1269)


In [14]:
logits_2 = torch.tensor([[-1.0, 1.0],
                         [-0.5, 1.5],
                         [-0.5, 1.5]])
targets_2 = torch.tensor([0, 1, 1])
loss_2 = torch.nn.functional.cross_entropy(logits_2, targets_2)
print(loss_2)

tensor(0.7936)


In [19]:
logits_3 = torch.tensor([[-1.0, 1.0],
                         [-0.5, 1.5],
                         [-0.5, 1.5]])
targets_3 = torch.tensor([0, 1, -100])
loss_3 = torch.nn.functional.cross_entropy(logits_3, targets_3)
print(loss_3)

tensor(1.1269)
