In [1]:
import torch

from multi_head_attention_wrapper import MultiHeadAttentionWrapper

In [2]:
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],
     [0.55, 0.87, 0.66],
     [0.57, 0.85, 0.64],
     [0.22, 0.58, 0.33],
     [0.77, 0.25, 0.10],
     [0.05, 0.80, 0.55]]
)

In [3]:
d_in = inputs.shape[1] # 입력 임베딩 크기
d_out = 2 # 출력 임베딩 크기
batch = torch.stack((inputs, inputs), dim=0)

In [4]:
torch.manual_seed(123)
context_length = batch.shape[1]
mha = MultiHeadAttentionWrapper(
    d_in, d_out, context_length, dropout=0.0, num_heads=2
)
context_vecs = mha(batch)

In [5]:
print(context_vecs)

tensor([[[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5846,  0.0103,  0.5813,  0.3105],
         [-0.6276, -0.0593,  0.6138,  0.3735],
         [-0.5658, -0.0827,  0.5463,  0.3539],
         [-0.5504, -0.0976,  0.5314,  0.3410],
         [-0.5286, -0.1068,  0.5069,  0.3449]],

        [[-0.4519,  0.2216,  0.4772,  0.1063],
         [-0.5846,  0.0103,  0.5813,  0.3105],
         [-0.6276, -0.0593,  0.6138,  0.3735],
         [-0.5658, -0.0827,  0.5463,  0.3539],
         [-0.5504, -0.0976,  0.5314,  0.3410],
         [-0.5286, -0.1068,  0.5069,  0.3449]]], grad_fn=<CatBackward0>)


In [6]:
print("context_vex.shape: ", context_vecs.shape)

context_vex.shape:  torch.Size([2, 6, 4])


In [7]:
a = torch.tensor([[[[0.2745, 0.6584, 0.2775, 0.8573],
                    [0.8993, 0.0390, 0.9268, 0.7388],
                    [0.7179, 0.7058, 0.9156, 0.4340]],
                   [[0.0772, 0.3565, 0.1479, 0.5331],
                    [0.4066, 0.2318, 0.4545, 0.9737],
                    [0.4606, 0.5159, 0.4220, 0.5786]]]])

In [8]:
a.shape

torch.Size([1, 2, 3, 4])

In [9]:
a.transpose(2, 3).shape

torch.Size([1, 2, 4, 3])

In [10]:
print( a @ a.transpose(2, 3))

tensor([[[[1.3208, 1.1631, 1.2879],
          [1.1631, 2.2150, 1.8424],
          [1.2879, 1.8424, 2.0402]],

         [[0.4391, 0.7003, 0.5903],
          [0.7003, 1.3737, 1.0620],
          [0.5903, 1.0620, 0.9912]]]])


In [11]:
first_head = a[0, 0, :, :]
first_res = first_head @ first_head.T
print(first_res)

tensor([[1.3208, 1.1631, 1.2879],
        [1.1631, 2.2150, 1.8424],
        [1.2879, 1.8424, 2.0402]])


In [12]:
second_head = a[0, 1, :, :]
second_res = second_head @ second_head.T
print(second_res)

tensor([[0.4391, 0.7003, 0.5903],
        [0.7003, 1.3737, 1.0620],
        [0.5903, 1.0620, 0.9912]])


In [13]:
from multi_head_attention import MultiHeadAttention

In [14]:
torch.manual_seed(123)
batch_size, context_length, d_in = batch.shape
d_out = 2

In [15]:
mha = MultiHeadAttention(d_in, d_out, context_length, dropout=0.0, num_heads=2)
context_vecs = mha(batch)

In [16]:
context_vecs

tensor([[[0.3190, 0.4858],
         [0.2943, 0.3897],
         [0.2856, 0.3593],
         [0.2693, 0.3873],
         [0.2639, 0.3928],
         [0.2575, 0.4028]],

        [[0.3190, 0.4858],
         [0.2943, 0.3897],
         [0.2856, 0.3593],
         [0.2693, 0.3873],
         [0.2639, 0.3928],
         [0.2575, 0.4028]]], grad_fn=<ViewBackward0>)

In [17]:
context_vecs.shape

torch.Size([2, 6, 2])