In [1]:
from util import preprocess, create_co_matrix, cos_similarity, ppmi

In [2]:
text = 'You say goodbye and I say hello.'
corpus, word_to_id, id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)
W = ppmi(C, verbose=True)

2.0% done
4.1% done
6.1% done
8.2% done
10.2% done
12.2% done
14.3% done
16.3% done
18.4% done
20.4% done
22.4% done
24.5% done
26.5% done
28.6% done
30.6% done
32.7% done
34.7% done
36.7% done
38.8% done
40.8% done
42.9% done
44.9% done
46.9% done
49.0% done
51.0% done
53.1% done
55.1% done
57.1% done
59.2% done
61.2% done
63.3% done
65.3% done
67.3% done
69.4% done
71.4% done
73.5% done
75.5% done
77.6% done
79.6% done
81.6% done
83.7% done
85.7% done
87.8% done
89.8% done
91.8% done
93.9% done
95.9% done
98.0% done
100.0% done


In [3]:
import numpy as np

In [4]:
np.set_printoptions(precision=3)

In [5]:
print('co occurrence matrix')
print(C)
print('-'*50)
print("PPMI")
print(W)

co occurrence matrix
[[0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]
--------------------------------------------------
PPMI
[[0.    1.807 0.    0.    0.    0.    0.   ]
 [1.807 0.    0.807 0.    0.807 0.807 0.   ]
 [0.    0.807 0.    1.807 0.    0.    0.   ]
 [0.    0.    1.807 0.    1.807 0.    0.   ]
 [0.    0.807 0.    1.807 0.    0.    0.   ]
 [0.    0.807 0.    0.    0.    0.    2.807]
 [0.    0.    0.    0.    0.    2.807 0.   ]]
